const ACTIONS = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    GET_TOKEN: "GET_TOKEN",
    GET_USER: "GET_USER",
    GET_ALL_USERS: "GET_ALL_USERS",
    PUSH_MESSAGE: "PUSH_MESSAGE",
};

export default ACTIONS;
