const ACTIONS = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    GET_TOKEN: "GET_TOKEN",
    GET_ALL_USERS: "GET_ALL_USERS",
    FIND_ALL_MENU: "FIND_ALL_MENU",
    CREATE_KIND_OF_FOOD: "CREATE_KIND_OF_FOOD",
    CREATE_FOOD: "CREATE_FOOD",
};

export default ACTIONS;
